services:
  - type: web
    name: telegram-ai-bot
    runtime: python
    buildCommand: ""
    startCommand: python3 poudelTeligramBot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false