services:
  - type: web
    name: telegram-ai-bot
    runtime: python
    buildCommand: ""
    startCommand: python poudel-telegram_ai_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
